server:
  port: 8090
spring:
  data:
    mongodb:
      username: airruppies
      password: Airr@#2024
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin